#ifndef INCLUDED_COM_SUN_STAR_TEXT_FOOTNOTELINESTYLE_HPP
#define INCLUDED_COM_SUN_STAR_TEXT_FOOTNOTELINESTYLE_HPP

#include "com/sun/star/text/FootnoteLineStyle.hdl"

#endif // INCLUDED_COM_SUN_STAR_TEXT_FOOTNOTELINESTYLE_HPP
