#ifndef INCLUDED_COM_SUN_STAR_CORBA_IOP_PROFILEIDGROUP_HPP
#define INCLUDED_COM_SUN_STAR_CORBA_IOP_PROFILEIDGROUP_HPP

#include "com/sun/star/corba/iop/ProfileIdGroup.hdl"

#endif // INCLUDED_COM_SUN_STAR_CORBA_IOP_PROFILEIDGROUP_HPP
