#ifndef INCLUDED_COM_SUN_STAR_CORBA_IOP_SERVICEIDGROUP_HPP
#define INCLUDED_COM_SUN_STAR_CORBA_IOP_SERVICEIDGROUP_HPP

#include "com/sun/star/corba/iop/ServiceIdGroup.hdl"

#endif // INCLUDED_COM_SUN_STAR_CORBA_IOP_SERVICEIDGROUP_HPP
