#ifndef INCLUDED_COM_SUN_STAR_AWT_MESSAGEBOXCOMMAND_HPP
#define INCLUDED_COM_SUN_STAR_AWT_MESSAGEBOXCOMMAND_HPP

#include "com/sun/star/awt/MessageBoxCommand.hdl"

#endif // INCLUDED_COM_SUN_STAR_AWT_MESSAGEBOXCOMMAND_HPP
