#ifndef INCLUDED_COM_SUN_STAR_SYNC_SYNCOPTIONS_HPP
#define INCLUDED_COM_SUN_STAR_SYNC_SYNCOPTIONS_HPP

#include "com/sun/star/sync/SyncOptions.hdl"

#endif // INCLUDED_COM_SUN_STAR_SYNC_SYNCOPTIONS_HPP
