#ifndef INCLUDED_COM_SUN_STAR_PLUGIN_PLUGINMODE_HPP
#define INCLUDED_COM_SUN_STAR_PLUGIN_PLUGINMODE_HPP

#include "com/sun/star/plugin/PluginMode.hdl"

#endif // INCLUDED_COM_SUN_STAR_PLUGIN_PLUGINMODE_HPP
