#ifndef INCLUDED_COM_SUN_STAR_UTIL_LOGGING_LOGLEVEL_HPP
#define INCLUDED_COM_SUN_STAR_UTIL_LOGGING_LOGLEVEL_HPP

#include "com/sun/star/util/logging/LogLevel.hdl"

#endif // INCLUDED_COM_SUN_STAR_UTIL_LOGGING_LOGLEVEL_HPP
