#ifndef INCLUDED_COM_SUN_STAR_INSTALLATION_PROTOCOLS_HPP
#define INCLUDED_COM_SUN_STAR_INSTALLATION_PROTOCOLS_HPP

#include "com/sun/star/installation/protocols.hdl"

#endif // INCLUDED_COM_SUN_STAR_INSTALLATION_PROTOCOLS_HPP
